project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"

freeze: true

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Tyler Burleigh"
description-meta: "I'm an AI engineer and this is my blog."
author-meta: "Tyler Burleigh"

website:
  title: "Tyler Burleigh"
  description: "{{< meta description-meta >}}"
  favicon: "/files/favico.png"
  site-url: "https://tylerburleigh.com"
  repo-url: "https://github.com/tylerburleigh/tylerburleigh-ath-quarto"

  google-analytics: "G-PRHQZ8HPLB"
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Research"
        file: research/index.qmd
    
    right:
      - icon: mastodon
        aria-label: mastodon
        href: https://fosstodon.org/users/tylerburleigh
        rel: me
      - icon: square
        aria-label: bluesky
        href: https://bsky.app/profile/tylerburleigh.bsky.social
        rel: me
      - icon: github
        aria-label: github
        href: https://github.com/tylerburleigh
        rel: me
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/tylerburleigh
        rel: me
      - icon: envelope
        aria-label: email
        href: mailto:tylerburleigh@gmail.com
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">[{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by/4.0/) {{< var years >}} Tyler Burleigh</span>
    center: |
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}}, [Quarto](https://quarto.org/), and the [ath-quarto](https://github.com/andrewheiss/ath-quarto) theme</span>

format:
  html:
    theme: 
      - html/ath.scss
      - _extensions/code-collapse/code-collapse.css
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    
extensions:
  - code-collapse